version: '3.4'
services:
    
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=jfuirI9324
    volumes:
      - ./temp/db:/var/lib/postgresql/data
  
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: config/containers/Dockerfile
    links:
      - app
    ports:
      - "81:81"